version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  fuzztest:
    executor: python/default
    steps:
      - checkout
      - run: 
          command: pip install requests
          name: dependencies
      - run:
          command: python .github/cyd.py
          name: fuzztest

workflows:
  main:
    jobs:
      - fuzztest
