version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  fuzztest:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python .github/cyd.py
          name: fuzztest

workflows:
  main:
    jobs:
      - fuzztest
